# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameDate', models.DateTimeField(verbose_name='Date of Game')),
                ('gameID', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=50, unique=True)),
                ('winsLosses', models.CharField(max_length=10)),
                ('teamName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='firstTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstTeam', to='NBAStats.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='secondTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondTeam', to='NBAStats.Team'),
        ),
    ]
