# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='gameDate',
        ),
        migrations.AddField(
            model_name='date',
            name='gamesOfDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamesOfDate', to='NBAStats.Game'),
        ),
    ]
