# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0002_auto_20161122_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='gamesOfDate',
        ),
        migrations.RemoveField(
            model_name='game',
            name='firstTeam',
        ),
        migrations.RemoveField(
            model_name='game',
            name='secondTeam',
        ),
        migrations.AddField(
            model_name='game',
            name='awayTeam',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='gameDate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NBAStats.Date'),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='lineScore',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
