# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0003_auto_20161212_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='awayTeam',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameID',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='homeTeam',
            field=models.CharField(default='', max_length=20),
        ),
    ]
