# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0004_auto_20161212_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gameDate',
        ),
    ]
