# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0005_remove_game_gamedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameDate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
